// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM5giBWya9OBp_3guyojE3EC8zdoxEOAM',
    appId: '1:809529399810:web:e0417a70b8b70ee2ce251b',
    messagingSenderId: '809529399810',
    projectId: 'mysafedaddy-63b66',
    authDomain: 'mysafedaddy-63b66.firebaseapp.com',
    storageBucket: 'mysafedaddy-63b66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdhHG8tytlHk-y62_Pyrnli5b_A6mdbm4',
    appId: '1:809529399810:android:96f6724d36ad671cce251b',
    messagingSenderId: '809529399810',
    projectId: 'mysafedaddy-63b66',
    storageBucket: 'mysafedaddy-63b66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUTJvYROtCBtbTKruV8_bpmzYa6HnEoNg',
    appId: '1:809529399810:ios:fde04cdd5f890d3cce251b',
    messagingSenderId: '809529399810',
    projectId: 'mysafedaddy-63b66',
    storageBucket: 'mysafedaddy-63b66.firebasestorage.app',
    iosBundleId: 'com.example.mysafedaddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUTJvYROtCBtbTKruV8_bpmzYa6HnEoNg',
    appId: '1:809529399810:ios:fde04cdd5f890d3cce251b',
    messagingSenderId: '809529399810',
    projectId: 'mysafedaddy-63b66',
    storageBucket: 'mysafedaddy-63b66.firebasestorage.app',
    iosBundleId: 'com.example.mysafedaddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM5giBWya9OBp_3guyojE3EC8zdoxEOAM',
    appId: '1:809529399810:web:b1ac0cedd3f44f87ce251b',
    messagingSenderId: '809529399810',
    projectId: 'mysafedaddy-63b66',
    authDomain: 'mysafedaddy-63b66.firebaseapp.com',
    storageBucket: 'mysafedaddy-63b66.firebasestorage.app',
  );
}
